name: gonmontir
on:
  workflow_dispatch:
  issues:
    types: [opened, edited, deleted, labeled, unlabeled]
jobs:
  stale:

    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v5
      with:
        stale-issue-message: 'Mensaje del issue'
